# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_remove_userinfo_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
